import { StyleProp } from "react-native";
import {
  CircleLayerStyle,
  FillExtrusionLayerStyle,
} from "@react-native-mapbox-gl/maps";

export const circleLayerStyles: StyleProp<CircleLayerStyle> = {
  circleColor: [
    "case",
    [">", ["get", "total"], 1000],
    "#800026",
    [">", ["get", "total"], 700],
    "#bd0026",
    [">", ["get", "total"], 500],
    "#e31a1c",
    [">", ["get", "total"], 400],
    "#fc4e2a",
    [">", ["get", "total"], 300],
    "#fd8d3c",
    [">", ["get", "total"], 200],
    "#feb24c",
    [">", ["get", "total"], 100],
    "#fed976",
    [">", ["get", "total"], 50],
    "#ffeda0",
    "#ffffcc",
  ],
  circleStrokeWidth: 2,
  circleStrokeColor: "#c9c9c9",
};

export const fillExtrusionLayerStyles: StyleProp<FillExtrusionLayerStyle> = {
  fillExtrusionColor: [
    "case",
    [">", ["get", "total"], 1000],
    "#800026",
    [">", ["get", "total"], 700],
    "#bd0026",
    [">", ["get", "total"], 500],
    "#e31a1c",
    [">", ["get", "total"], 400],
    "#fc4e2a",
    [">", ["get", "total"], 300],
    "#fd8d3c",
    [">", ["get", "total"], 200],
    "#feb24c",
    [">", ["get", "total"], 100],
    "#fed976",
    [">", ["get", "total"], 50],
    "#ffeda0",
    "#ffffcc",
  ],
  fillExtrusionHeight: [
    "case",
    [">", ["get", "total"], 1000],
    290,
    [">", ["get", "total"], 700],
    245,
    [">", ["get", "total"], 500],
    200,
    [">", ["get", "total"], 400],
    140,
    [">", ["get", "total"], 300],
    105,
    [">", ["get", "total"], 200],
    80,
    [">", ["get", "total"], 100],
    35,
    [">", ["get", "total"], 50],
    17.5,
    3.5,
  ],
};
